### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [penland365/gh#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by jnd71** [comment]
Nope! I'm working now to yank it out.

**Comment by jnd71** [comment]
Addressed by https://github.com/penland365/gh/pull/10
